---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: nginx
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: nginx
    version: 5.2.2