---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: nginx
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: nginx
    version: 5.1.12
  values:
    image:
      repository: bitnami/nginx
      tag: 1.16.1